<div class="bottom-box-3">
    <div class="box-3-text title">
        <b>ON-SALE PRODUCTS</b>
    </div>

    <div class="box-3-product">
        <a class="box-3-item" href="">
            <div class="box-3-item-img">
                <img src="<?php echo $this->getSkinUrl('images/pro1.png') ?>" alt="">
            </div>
            <div class="box-3-item-text">
                <p style="color: gray; margin: 0;">Macbook, Laptop</p>
                <p style="margin: 0;">
                    <b>Apple Macbook Air Retina 23''</b>
                </p>
                <p style="color:#d13638;"><b>$290.00</b></p>
            </div>
        </a>



        <a class="box-3-item" href="">
            <div class="box-3-item-img">
                <img src="<?php echo $this->getSkinUrl('images/pro2.png') ?>" alt="">
            </div>
            <div class="box-3-item-text">
                <p style="color: gray; margin: 0;">Macbook, Laptop</p>
                <p style="margin: 0;"><b>Apple Macbook Pro Retina 23''</b></p>
                <p style="color:#d13638;"><b>$300.00</b></p>
            </div>
        </a>
    </div>
</div>