<div class="bottom-box-2">
    <ul class="box-2-left">
        <li class="title">
            <b><?php echo $this->__('INFORMATION'); ?></b>
        </li>
        <li class="box-2-left-item">
            <a href="#"><?php echo $this->__('About Us'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="#"><?php echo $this->__('Contact Us'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="#"><?php echo $this->__('All Collection'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="#"><?php echo $this->__('Privacy policy'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="#"><?php echo $this->__('Term &amp; Condition'); ?></a>
        </li>
    </ul>
    <ul class="box-2-right">
        <li class="title">
            <b><?php echo $this->__('CATEGORIES'); ?></b>
        </li>
        <li class="box-2-left-item">
            <a href="#"><?php echo $this->__('Fashion'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="#"><?php echo $this->__('Electronics'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="#"><?php echo $this->__('Funitured &amp; Decor'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="#"><?php echo $this->__('Jewelry &amp; Watches'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="#"><?php echo $this->__('Health &amp; Beauty'); ?></a>
        </li>
    </ul>
</div>