
<div class="bottom-box-2">
    <ul class="box-2-left">
        <li class="title">
            <b><?php echo $this->__('INFORMATION'); ?></b>
        </li>
        <li class="box-2-left-item">
            <a href="<?php echo $this->getUrl('about-magento-demo-store') ?>"><?php echo $this->__('About Us'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="<?php echo $this->getUrl('contacts') ?>"><?php echo $this->__('Contact Us'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="#"><?php echo $this->__('All Collection'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="<?php echo $this->getUrl('privacy-policy-cookie-restriction-mode') ?>"><?php echo $this->__('Privacy policy'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="#"><?php echo $this->__('Term &amp; Condition'); ?></a>
        </li>
    </ul>
    <ul class="box-2-right">
        <li class="title">
            <b><?php echo $this->__('CATEGORIES'); ?></b>
        </li>
        <li class="box-2-left-item">
            <a href="<?php echo $this->getUrl('women.html') ?>"><?php echo $this->__('Women'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="<?php echo $this->getUrl('men.html') ?>"><?php echo $this->__('Men'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="<?php echo $this->getUrl('accessories.html') ?>"><?php echo $this->__('Accessories'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="<?php echo $this->getUrl('home-decor.html') ?>"><?php echo $this->__('Home & Decor'); ?></a>
        </li>
        <li class="box-2-left-item">
            <a href="<?php echo $this->getUrl('vip.html') ?>"><?php echo $this->__('VIP'); ?></a>
        </li>
    </ul>
</div>