<div class="bottom-box-3">
    <div class="box-3-text title">
        <b>ON-SALE PRODUCTS</b>
    </div>

    <div class="box-3-product">
        <div class="box-3-item">
            <div class="box-3-item-img">
                <img src="<?php echo $this->getSkinUrl('images/pro1.png') ?>" alt="">
            </div>
            <div class="box-3-item-text">
                <p style="color: gray; margin: 0;">Macbook, Laptop</p>
                <p style="margin: 0;">
                    <b>Apple Macbook 23''</b>
                </p>
                <p style="color:#d13638;"><b>$290.00</b></p>
            </div>
        </div>
        <div class="box-3-item">
            <div class="box-3-item-img">
                <img src="<?php echo $this->getSkinUrl('images/pro2.png') ?>" alt="">
            </div>
            <div class="box-3-item-text">
                <p style="color: gray; margin: 0;">Macbook, Laptop</p>
                <p style="margin: 0;"><b>Apple Macbook 23''</b></p>
                <p style="color:#d13638;"><b>$290.00</b></p>
            </div>
        </div>
    </div>
</div>