
<?php if($this->getCurrencyCount()>1): ?>
    <div class="form-drop">
        <ul id="select-language" title="<?php echo $this->__('Language') ?>" class="dropDownMenu">
        <li class="default-item"><?php echo $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode(); ?>

            <ul class="drop-item">
                <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
                <li>
                    <a href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>" onclick="setLocation(this.value);">
                        <?php echo $_code ?>
                        <?php
                        $currencySymbol = Mage::app()->getLocale()->currency($_code)->getSymbol();
                        ?>
                        <?php echo $currencySymbol; ?>
                    </a>
                </li>
                <?php endforeach; ?>
            </ul>

        </li>
        </ul>
    </div>
<?php endif; ?>