
<?php var_dump($this->getCurrencyCount()); ?>
<?php if(count($this->getStores())>1): ?>
    <?php
    $lis = "";
    $selCurrency = $this->__('Currency');
    foreach ($this->getStores() as $_lang):
        if($_lang->getId() == $this->getCurrentStoreId()){
            $selCurrency = $this->escapeHtml($_lang->getName());
        }
        $lis .= '<li><a href="'.$_lang->getCurrentUrl().'">'.$this->escapeHtml($_lang->getName()).'</a></li>';
    endforeach;
    ?>

    <div class="form-language">
        <ul id="select-language" title="<?php echo $this->__('Language') ?>" class="dropDownMenu">
            <li class="default-item"><a><?php echo $selCurrency ?></a>
                <ul class="language-item">
                    <?php echo $lis ?>
                </ul>
            </li>
        </ul>
    </div>
<?php endif; ?>